[build]
base = "frontend"
command = "npm run build"
publish = "build"

[[redirects]]
from = "/api/*"
to = "https:http://localhost:5000/"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


